// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/err.proto

package errs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 错误码
type StateCode struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateCode) Reset()         { *m = StateCode{} }
func (m *StateCode) String() string { return proto.CompactTextString(m) }
func (*StateCode) ProtoMessage()    {}
func (*StateCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_a849e50cf3babed7, []int{0}
}

func (m *StateCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateCode.Unmarshal(m, b)
}
func (m *StateCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateCode.Marshal(b, m, deterministic)
}
func (m *StateCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateCode.Merge(m, src)
}
func (m *StateCode) XXX_Size() int {
	return xxx_messageInfo_StateCode.Size(m)
}
func (m *StateCode) XXX_DiscardUnknown() {
	xxx_messageInfo_StateCode.DiscardUnknown(m)
}

var xxx_messageInfo_StateCode proto.InternalMessageInfo

func (m *StateCode) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StateCode) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*StateCode)(nil), "error.StateCode")
}

func init() { proto.RegisterFile("proto/err.proto", fileDescriptor_a849e50cf3babed7) }

var fileDescriptor_a849e50cf3babed7 = []byte{
	// 95 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x2d, 0x2a, 0xd2, 0x03, 0xb3, 0x84, 0x58, 0x53, 0x8b, 0x8a, 0xf2, 0x8b, 0x94,
	0x74, 0xb9, 0x38, 0x83, 0x4b, 0x12, 0x4b, 0x52, 0x9d, 0xf3, 0x53, 0x52, 0x85, 0xf8, 0xb8, 0x98,
	0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x98, 0x32, 0x53, 0x84, 0x04, 0xb8, 0x98,
	0x73, 0x8b, 0xd3, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x40, 0xcc, 0x24, 0x36, 0xb0, 0x66,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x93, 0xef, 0xd9, 0x4f, 0x00, 0x00, 0x00,
}
